#!/bin/bash
# Installs the 3CX Voicemail Manager on a fresh 3CX server.
#
# Usage: copy this whole directory to the target server first (see DEPLOY.md),
# then on the target server run:  sudo ./install.sh
#
# This script handles the mechanical, repeatable parts. It deliberately does
# NOT touch the firewall (nftables.conf is 3CX's own managed config — see
# DEPLOY.md for that step) and does NOT reuse this server's .env verbatim —
# SECRET_KEY and ADMIN_EXTENSIONS must be specific to the target server.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VOICEMAIL_ROOT_DEFAULT="/var/lib/3cxpbx/Instance1/Data/Ivr/Voicemail/Extensions"
NGINX_SNIPPETS_DIR="/var/lib/3cxpbx/Bin/nginx/conf/snippets"
NGINX_SNIPPET_FILE="${NGINX_SNIPPETS_DIR}/60-vm-manager.conf"
PORT_DEFAULT=8080

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root (sudo ./install.sh)." >&2
  exit 1
fi

echo "== Checking for the phonesystem OS user (created by 3CX itself) =="
if ! id phonesystem >/dev/null 2>&1; then
  echo "ERROR: no 'phonesystem' OS user found. This doesn't look like a 3CX server." >&2
  echo "This app relies on 3CX's own OS user for passwordless DB access via peer auth." >&2
  exit 1
fi
echo "OK: phonesystem user present."

echo "== Checking the voicemail audio path =="
if [ -d "$VOICEMAIL_ROOT_DEFAULT" ]; then
  echo "OK: found $VOICEMAIL_ROOT_DEFAULT"
else
  echo "WARNING: $VOICEMAIL_ROOT_DEFAULT does not exist on this server."
  echo "3CX doesn't document this path — it was found by trial on the original server."
  echo "Find the real path before going further, e.g.:"
  echo "  find /var/lib/3cxpbx -type d -iname Extensions"
  echo "Then set VOICEMAIL_ROOT in .env accordingly."
fi

echo "== Checking Postgres peer auth for the phonesystem role =="
if su - phonesystem -s /bin/bash -c "psql -d database_single -c 'select 1;'" >/dev/null 2>&1; then
  echo "OK: phonesystem can connect to database_single via peer auth."
else
  echo "WARNING: could not connect as phonesystem to database_single."
  echo "Check that database_single exists and pg_hba.conf allows 'local all all peer'."
fi

echo "== Installing Python dependencies system-wide =="
if ! command -v pip3 >/dev/null 2>&1; then
  apt-get update
  apt-get install -y python3-pip
fi
pip3 install --break-system-packages -q \
  fastapi "uvicorn[standard]" psycopg2-binary itsdangerous python-multipart python-dotenv requests \
  faster-whisper pywebpush "pyjwt[crypto]"

echo "== Setting up .env =="
if [ -f "$APP_DIR/.env" ]; then
  echo "$APP_DIR/.env already exists — leaving it alone."
else
  SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
  cat > "$APP_DIR/.env" <<EOF
# 3CX Voicemail Manager configuration — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# DATABASE_URL uses a Unix-socket connection authenticated via Postgres peer auth.
DATABASE_URL=postgresql://phonesystem@/database_single?host=/var/run/postgresql
SECRET_KEY=${SECRET_KEY}

# REQUIRED: comma-separated list of extensions allowed to manage groups/settings.
ADMIN_EXTENSIONS=

VOICEMAIL_ROOT=${VOICEMAIL_ROOT_DEFAULT}
APP_DB_PATH=${APP_DIR}/vm_manager.db

# REQUIRED: native MWI for notify, delete, and other administrator functions.
# THREECX_ADMIN_EXTENSION must be a System Owner extension. THREECX_PBX_URL
# is the full origin, e.g. https://pbx.example.com:5001.
THREECX_PBX_URL=
THREECX_ADMIN_EXTENSION=
THREECX_ADMIN_PASSWORD=

# App only reachable via the nginx snippet install.sh installs (this port,
# behind https://<host>/vm-manager/ -- see 60-vm-manager.conf). Only change
# HOST to 0.0.0.0 for direct external access, and open the firewall yourself.
HOST=127.0.0.1
PORT=${PORT_DEFAULT}

SESSION_MAX_AGE_SECONDS=28800
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_MINUTES=15

# --- Microsoft (Entra ID) sign-in for the web UI --------------------------
# App registration platform must be "Single-page application" with redirect
# URI https://<this-host>/vm-manager/callback.html -- see app/config.py's
# comment for why this is a secret-free public-client flow. Leave unset for
# PIN-only login.
#MS_AUTH_TENANT_ID=
#MS_AUTH_CLIENT_ID=
#PIN_LOGIN_ENABLED=true
#MS_AUTH_OVERRIDE_EMAILS=

# --- Yealink XML Browser (visual voicemail on the phone screen) ----------
# PUBLIC_BASE_URL defaults to THREECX_PBX_URL + /vm-manager (see
# app/config.py) -- correct as long as this server's nginx mount point is
# the standard /vm-manager/. Only set it explicitly if that's not the case.
#PUBLIC_BASE_URL=
YEALINK_TOKEN_MAX_AGE_SECONDS=300
YEALINK_TIME_ZONE=America/Vancouver

# --- PJSUA2 phone playback (needs build_pjsua2.sh -- see DEPLOY.md 2.5) --
# Leave unset to disable the phone-call/playback buttons. Extension creds
# from the 3CX admin console (Extensions -> the extension -> Generic/SIP).
#PBX_HOST=127.0.0.1
#PBX_DOMAIN=
#PBX_PORT=5060
#PBX_TRANSPORT=udp
#EXTENSION=
#AUTH_ID=
#PASSWORD=

# --- Voicemail transcription ---------------------------------------------
# Enable/disable and engine choice live in the app's own SQLite DB, set via
# Settings > Transcription in the web UI -- not here. OPENAI_API_KEY unset
# disables the OpenAI engine option. WHISPER_* defaults: model "tiny"
# (~320MB resident), int8, capped at 1024MB RSS via a polling watchdog.
#OPENAI_API_KEY=
#OPENAI_TRANSCRIBE_MODEL=gpt-4o-transcribe
#WHISPER_MODEL_SIZE=tiny
#WHISPER_MEMORY_LIMIT_MB=1024

# --- Notification delivery -------------------------------------------------
# Enable/disable for SMTP and PWA push each live in the app's own SQLite DB,
# set via Settings > Notifications in the web UI (both start OFF) -- not
# here. Leaving these unset just means that toggle stays unavailable (400 on
# save) until they're filled in.
#SMTP_HOST=
#SMTP_PORT=587
#SMTP_USERNAME=
#SMTP_PASSWORD=
#SMTP_FROM=
#SMTP_USE_TLS=true
#
# Generate a VAPID key pair with: python3 -m py_vapid --gen (after installing
# pywebpush, which pulls in py-vapid)
#VAPID_PUBLIC_KEY=
#VAPID_PRIVATE_KEY=
#VAPID_CONTACT_EMAIL=
EOF
  echo "Created $APP_DIR/.env with a freshly generated SECRET_KEY."
  echo "!! You MUST edit ADMIN_EXTENSIONS in .env before this is usable. !!"
fi

echo "== Setting ownership =="
chown -R phonesystem:phonesystem "$APP_DIR"

echo "== Installing systemd service =="
sed "s#/opt/vm-manager#${APP_DIR}#g" "$APP_DIR/vm-manager.service" > /etc/systemd/system/vm-manager.service
chown root:root /etc/systemd/system/vm-manager.service
systemctl daemon-reload
systemctl enable vm-manager.service

echo "== Installing nginx reverse-proxy snippet =="
# 3CX's own nginx already terminates TLS on 443 (open in nftables by 3CX
# itself) and includes conf/snippets/*.conf. Dropping a snippet there gets
# us https://<host>/vm-manager/ for free with no firewall changes needed —
# this is app-managed like vm-manager.service above, don't hand-edit it,
# re-running install.sh will overwrite it.
APP_PORT="$(grep -E '^PORT=' "$APP_DIR/.env" 2>/dev/null | cut -d= -f2)"
APP_PORT="${APP_PORT:-$PORT_DEFAULT}"
if [ -d "$NGINX_SNIPPETS_DIR" ]; then
  cat > "$NGINX_SNIPPET_FILE" <<EOF
location = /vm-manager {
    return 301 \$scheme://\$host/vm-manager/;
}

location /vm-manager/ {
    proxy_pass http://127.0.0.1:${APP_PORT}/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Proto \$scheme;
}
EOF
  chown root:root "$NGINX_SNIPPET_FILE"
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx
    echo "OK: installed $NGINX_SNIPPET_FILE and reloaded nginx."
  else
    echo "WARNING: nginx config test failed after installing the snippet — check 'nginx -t'." >&2
    echo "Not reloading nginx automatically; fix the config and reload manually." >&2
  fi
else
  echo "WARNING: $NGINX_SNIPPETS_DIR not found. This doesn't look like a standard 3CX nginx layout."
  echo "Skipping nginx snippet install — you'll need to reverse-proxy to 127.0.0.1:${APP_PORT} yourself,"
  echo "or set HOST=0.0.0.0 in .env and open the firewall for direct access."
fi

echo "== Installing sip-reject-watch.service (mandatory) =="
# Without this, phone_service.py can't distinguish a real answer from 3CX
# transparently rerouting a rejected/no-answer call to its own internal
# voicemail app -- 3CX reports a clean 200 OK/CONFIRMED to our SIP leg
# either way (see sip_reject_watch.py's own docstring). Needs its own unit
# because it requires CAP_NET_RAW, which vm-manager.service deliberately
# doesn't have.
PBX_IFACE="$(ip -o -4 route show to default | awk '{print $5; exit}')"
if [ -z "$PBX_IFACE" ]; then
  echo "WARNING: couldn't auto-detect the PBX-facing network interface (no default route found)." >&2
  echo "Leaving sip_reject_watch.py's IFACE as-is -- check/set it manually before trusting this service." >&2
else
  CURRENT_IFACE="$(sed -n 's/^IFACE = "\(.*\)"$/\1/p' "$APP_DIR/sip_reject_watch.py")"
  if [ "$CURRENT_IFACE" != "$PBX_IFACE" ]; then
    sed -i "s/^IFACE = \".*\"/IFACE = \"${PBX_IFACE}\"/" "$APP_DIR/sip_reject_watch.py"
    echo "Set IFACE=\"${PBX_IFACE}\" in sip_reject_watch.py (auto-detected from the default route)."
  fi
fi
chown phonesystem:phonesystem "$APP_DIR/sip_reject_watch.py"
sed "s#/opt/vm-manager#${APP_DIR}#g" "$APP_DIR/sip-reject-watch.service" > /etc/systemd/system/sip-reject-watch.service
chown root:root /etc/systemd/system/sip-reject-watch.service
systemctl daemon-reload
systemctl enable sip-reject-watch.service
systemctl restart sip-reject-watch.service
SOCKET_OK=0
for _ in 1 2 3 4 5; do
  if sudo -u phonesystem python3 -c "
import socket
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(2)
s.connect('/run/sip-reject-watch/query.sock')
s.sendall(b'0 0')
s.recv(256)
" >/dev/null 2>&1; then
    SOCKET_OK=1
    break
  fi
  sleep 1
done
if [ "$SOCKET_OK" -eq 1 ]; then
  echo "OK: sip-reject-watch.service is up and its query socket answers."
else
  echo "WARNING: sip-reject-watch.service didn't answer on its query socket after 5s — check 'systemctl status sip-reject-watch.service'." >&2
fi
echo "NOTE: this only confirms the service is up, not that it's actually seeing SIP traffic on ${PBX_IFACE:-<unknown>}."
echo "Verify with: tcpdump -i ${PBX_IFACE:-<iface>} -n \"port 5060\" during a real call, per DEPLOY.md."

echo
echo "================================================================"
echo "Almost done. Before starting the service:"
echo "  1. Edit $APP_DIR/.env and set ADMIN_EXTENSIONS, THREECX_PBX_URL,"
echo "     THREECX_ADMIN_EXTENSION, and THREECX_ADMIN_PASSWORD (all required —"
echo "     the app will not start without the THREECX_* trio set)."
echo "  2. Start the app:"
echo "       systemctl start vm-manager.service"
echo "       systemctl status vm-manager.service"
echo "  3. Log in at https://<this-server>/vm-manager/"
echo "================================================================"
